"""Initial migration

Revision ID: 09a7957fc6e9
Revises: 
Create Date: 2026-07-07 17:02:31.073508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a7957fc6e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('program_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_label', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_info',
    sa.Column('docs_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=True),
    sa.Column('docs_name', sa.String(), nullable=False),
    sa.Column('size_kb', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['packet_id'], ['request_status.id'], name='fk_paket_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('docs_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents_info')
    op.drop_table('request_status')
    # ### end Alembic commands ###
